apiVersion: v1
kind: Service
metadata:
  name: service-k8s-spring
spec:
  type: NodePort
  selector:
    app: k8s-spring
  ports:
      # By default the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      #targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      #nodePort: 32500